dotfiles_dir = "dotfiles"

[settings]
prehooks = [
    "mkdir -p ~/.config/zellij"
]

[settings.dots]
# Shell Setup
alacritty = { source = "shell/alacritty.toml", target = ".alacritty.toml" }
zellij = { source = "shell/zellij.kdl", target = ".config/zellij/config.kdl" }
zsh = { source = "shell/.zshrc", target = ".zshrc" }
starship = { source = "shell/starship.toml", target = ".config/starship.toml" }

# NeoVim
neovim = { source = "nvim", target = ".config/nvim" }
